services:
  port_server:
    environment:
      ADDR: ":50052"
    build: ./server
    volumes:
     - "data:/data"
    networks:
      - back-tier

  port_cli:
    build: ./cli
    environment:
      ADDR: ":8082"
      GRPC_ADDR: "port_server:50052"
    depends_on:
      - port_server
    volumes:
      - "infile:/in"
    ports:
      - "8081:8080"
    networks:
      - back-tier


volumes:
  data:
  infile:

networks:
  back-tier: